config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'netivot#index'

  resources :network
  resources :team
  resources :contact
  resources :resources
  resources :events, only: [:index]
  resources :join

  namespace :admin do
    root to: 'dashboards#index'

    resources :events, only: [:index, :new, :create, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :email, with: /@/

  validates :password, length: { minimum: 8 }, unless: 'password.nil?'
  validates_confirmation_of :password

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  has_many :events
  belongs_to :member

  # validate :first_name

  def is_attending?(event)
    event.attendees.include?(self)
  end

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :attendees

  validates :name, presence: true
  validate :start_at_time
  validate :end_at_time
  validate :start_at_date
  validate :end_at_date
  validate :location_display_string
  validate :description
  validate :location_id
  validate :registration_link

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessor :name, :capacity

end

app/models/member.rb
class Member < ActiveRecord::Base

  has_one :attendee
  delegate :first_name, to: :attendee

  validate :first_name
  validate :email

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController

  before_filter :authenticate_admin!

  def save_as_csv(filename)
    headers['Content-Disposition'] = %Q[attachment; filename=#{filename}.csv]
    headers['Content-Type'] ||= 'text/csv'
  end

  private


end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
  # @event.listed_by_user = current_user

    if @event.valid?
      @event.save!
      flash[:notice] = "#{@event.name} added."
      redirect_to action: :index
    else
      flash.now[:alert] = "Bad event. #{@event.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      flash[:notice] = "Event updated."
      redirect_to action: :index
    else
      flash.now[:alert] = "Event update failed. #{@event.errors.full_messages.join(', ')}"
      render :edit
    end

  end


  private

  def parse_datetimes_from_split_params
    event_params['start_at'] = parse_datetime( event_params[:start_time] )
    event_params['end_at'] = parse_datetime( event_params[:end_time] )
  end

  def parse_datetime(time)
    Time.strptime(event_params[:date] + time, '%m-%d-%Y%l:%M %p') rescue return
  end

  def event_params
    params.require(:event).permit(:name, :start_at_time, :end_at_time, :start_at_date, :end_at_date,
      :location_display_string, :description, :location_id, :registration_link)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def index
    @members = Attendee.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.create(member_params)
  # @member.listed_by_user = current_user

    if @member.valid?
      @member.save!
      flash[:notice] = "#{@member.first_name} added."
      redirect_to action: :index
    else
      flash.now[:alert] = "Bad member. #{@member.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def first_name
    @member = Member.find(params[:id])
    @member.first_name
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
  # @event.listed_by_user = current_user

    if @event.valid?
      @event.save!
      flash[:notice] = "#{@event.name} added."
      redirect_to action: :index
    else
      flash.now[:alert] = "Bad event. #{@event.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      flash[:notice] = "Event updated."
      redirect_to action: :index
    else
      flash.now[:alert] = "Event update failed. #{@event.errors.full_messages.join(', ')}"
      render :edit
    end

  end


  private

  def parse_datetimes_from_split_params
    event_params['start_at'] = parse_datetime( event_params[:start_time] )
    event_params['end_at'] = parse_datetime( event_params[:end_time] )
  end

  def parse_datetime(time)
    Time.strptime(event_params[:date] + time, '%m-%d-%Y%l:%M %p') rescue return
  end

  def event_params
    params.require(:event).permit(:name, :start_at_time, :end_at_time, :start_at_date, :end_at_date,
      :location_display_string, :description, :location_id, :registration_link)
  end


end

app/controllers/join_controller.rb
class JoinController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.create(member_params)
  # @member.listed_by_user = current_user

    if @member.valid?
      @member.save!
      flash[:notice] = "#{@member.name} added."
      redirect_to action: :index
    else
      flash.now[:alert] = "Bad member. #{@member.errors.full_messages.join(', ')}"
      render :new
    end
  end

end

app/controllers/netivot_controller.rb
class NetivotController < ApplicationController
  def index
  end
end

app/controllers/network_controller.rb
class NetworkController < ApplicationController
  def index
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  def index
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/events/_form.html.haml
%h4 New Event

= form_for [:admin, @event] do |f|
  .row
    .large-7.columns
      = f.label :name
      = f.text_field :name
      = f.label :location_display_string
      = f.text_field :location_display_string
      .row
        .large-8.columns
          = f.label :registration_link
          = f.text_field :registration_link

      .row
        .large-3.medium-4.small-12.left.columns
          = f.label :date
          = f.text_field :start_at_date
        .large-3.medium-4.small-6.left.columns
          .start.timepicker
            = f.label :start_at_time
            = f.text_field :start_at_time
        .large-3.medium-4.small-6.left.columns
          .end.timepicker
            = f.label :end_at_time
            = f.text_field :end_at_time
      .row
        .large-3.medium-4.small-12.left.columns
          = f.label :location_id
          = f.number_field :location_id
    .large-12.columns
      = f.label :description
      = f.text_area :description, rows: 15
      .row
        .large-3.small-2.columns.right.text-right
          = f.submit 'Save', class: 'small button', data: { disable_with: 'Please wait...' }

:javascript
  $('#event_start_time').combodate();
  $('#event_end_time').combodate();
  $('#event_date').fdatepicker({
    format: 'mm-dd-yyyy',
    startDate: new Date()
  });

app/views/admin/events/index.html.haml
%section#content
  %h2 Events
  - if @events
    - @events.each do |event|
      %li= event.name
      %p.close X
  - else
    %p We don't have any upcoming events scheduled as of #{Time.now.strftime('%m/%d/%Y')}, but please check back soon!

%br

  = button_to("New Event", new_admin_event_path, method: :get)

app/views/admin/events/new.html.haml
%section#content
  = render 'form'

app/views/events/_form.html.haml
%h4 New Event

= form_for @event do |f|
  .row
    .large-7.columns
      = f.label :name
      = f.text_field :name
      = f.label :location_display_string
      = f.text_field :location_display_string
      .row
        .large-8.columns
          = f.label :registration_link
          = f.text_field :registration_link

      .row
        .large-3.medium-4.small-12.left.columns
          = f.label :date
          = f.text_field :start_at_date
        .large-3.medium-4.small-6.left.columns
          .start.timepicker
            = f.label :start_at_time
            = f.text_field :start_at_time
        .large-3.medium-4.small-6.left.columns
          .end.timepicker
            = f.label :end_at_time
            = f.text_field :end_at_time
      .row
        .large-3.medium-4.small-12.left.columns
          = f.label :location_id
          = f.text_field :location_id
    .large-12.columns
      = f.label :description
      = f.text_area :description, rows: 15
      .row
        .large-3.small-2.columns.right.text-right
          = f.submit 'Save', class: 'small button', data: { disable_with: 'Please wait...' }

:javascript
  $('#event_start_time').combodate();
  $('#event_end_time').combodate();
  $('#event_date').fdatepicker({
    format: 'mm-dd-yyyy',
    startDate: new Date()
  });

app/views/events/index.html.haml
%section#content
  %h2 Events
  - if @events
    - @events.each do |event|
      %div.event.12u
        %h4= event.name
        %p
          %span= event.location_id
          %br
          %span= event.start_at_date
          %br
          %span= event.description
      %br
  - else
    %p We don't have any upcoming events scheduled as of #{Time.now.strftime('%m/%d/%Y')}, but please check back soon!

%br

app/views/join/new.html.erb
<section id="content">
  <h3>Join Netivot</h3>
  <ul>
    <li><%= link_to("Join the email list", "https://docs.google.com/forms/d/1Gl2ErtW5cS5MrAEjVNmVqT_XOAodXkw9sBiqGBiOMJ4/viewform?edit_requested=true") %> to get updates about upcoming events.</li>
    <li><%= mail_to("netivotboston@gmail.com", "Email us") %> to get added to our Facebook group, which has privacy settings so that only members can see that the group exists or who the members are.</li>
  </ul>
  <h5>Your information is completely confidential and will not be shared with others.</h5>
</section>

app/views/netivot/index.html.erb
<!-- Content -->
  <section id="content">
    <%= image_tag("israel-path.jpg", class: "image fit") %>
    <h3>We Are Netivot</h3>
    <p>We are Netivot, a group of LGBTQ Jews in the Boston, New York, and Tel Aviv areas who are engaged in traditional Judaism. Some of us come from Orthodox or traditional backgrounds, others are currently exploring a traditional Jewish identity. Our mission is to create a space to explore the intersection between our LGBTQ and traditional Jewish identities, and to move the traditional community towards greater understanding and acceptance of LGBTQ Jews.</p>
    <p>The literal translation of Netivot is “paths”. Netivot was created because of a need to create another path for LGBTQ Jews who have connections to traditional Judaism. Netivot serves as a warm, welcoming community for LGBTQ Jews interested in growing and learning in a traditionally minded environment. We are also committed to moving the traditional community to greater understanding and acceptance of LGBTQ Jews.</p>
  </section>

app/views/network/new.html.erb
<!-- Content -->
  <section id="content">
    <h3>Netivot Network</h3>
    <p>We’re excited to announce the launch of our new program, Netivot Network! Netivot Network connects you to other Netivot members to foster one-on-one connections outside of our monthly events. Whether you’re looking for a chavruta, someone to talk to about queer/Jewish things, or just a new friend to get coffee with, we can pair you up with another Netivot member with similar goals. You can meet over email, Skype, or in person. We’re excited to provide this opportunity for you, and we’re looking forward to seeing where you take these connections. To sign up, please fill out the form <%= link_to("here", "https://docs.google.com/forms/d/e/1FAIpQLSfFZ7s8W7T9KmQ4yNepaDdajHFh7dtlR0QDtKVujC6IEU8NIQ/viewform") %>. As always, please email <%= mail_to("netivotboston@gmail.com", "netivotboston@gmail.com") %> with any questions or concerns.
  </section>

app/views/resources/new.html.erb
<section id="content">
  <h3>Resources</h3>
  <p> <%= link_to('Keshet', 'http://www.keshetonline.org/') %> - Jewish LGBT organization in Boston and San Francisco</p>
  <p> <%= link_to('JQYouth', 'http://www.jqyouth.org/') %> – Orthodox LGBT Youth organization based in New York</p>
  <p> <%= link_to('Eshel', 'http://www.eshelonline.org/') %> – National Orthodox LGBT organization
  <p> <%= link_to('Yeshiva Inclusion Project (YIP)', 'https://yeshivainclusionproject.org/') %> – resource for LGBT Orthodox students applying to Israel gap year programs
  <p> <%= link_to('Or Chayim', 'https://orchayim.org/') %> – minyan for unaffiliated, traditional and Orthodox LGBTQ Jews located in New York City’s Upper West Side</p>
</section>

app/views/team/new.html.erb
<!-- Content -->
  <section id="content">
    <h3>Board Members</h3>
    <%= image_tag("avi.jpg", class: "image left") %>
    <h4>Avi Fuld, President, International</h4>
    <p>As one of the original founders of Netivot, Avi has spent countless hours dedicated to Netivot's success, including heading finances and collaborative events. Avi is excited to take Netivot to the next level by overseeing the whole operation as well as creating a Brooklyn branch.</p>
    <br />
    <%= image_tag("israel-path.jpg", class: "image left") %>
    <h4>Zahava Stern, Vice President, International; President, Boston</h4>
    <p>As one of the original founders, Zahava has worked on every aspect of Netivot's wonderful events, including maintaining the website and creating graphics. In addition to VP of the international board, Zahava is excited to be the first official president of the local Boston board.</p>
    <br />
    <%= image_tag("israel-path.jpg", class: "image left") %>
    <h4>Morris Alper, Public Relations, International</h4>
    <p>Even if you haven't yet met Morris in person, you likely have experienced him online. As one of the original founders Morris has been crucial to both the creation and growth of Netivot by not only inviting everyone to the very first meet-up, but also by heading every meeting since. Morris is excited about starting a new chapter in Tel Aviv.</p>
    <br />
    <%= image_tag("israel-path.jpg", class: "image left") %>
    <h4>Bess Beller-Levesque, Treasurer and Secretary, International; Treasurer, Boston</h4>
    <p>Bess has been with Netivot since its creation, hosting Shabbat dinners on a consistent basis, always with a warm and welcoming smile. Her positive attitude and organizational skills are essential for Netivot's current transition and growth.</p>
    <br />
    <%= image_tag("kristin.jpg", class: "image left") %>
    <h4>Kristin Ruben, Webmaster, International</h4>
    <p>Since attending her first Shabbat dinner in 2015, Kristin fell in love with Netivot and was hooked for life. She's excited to use her new programming skills to re-vamp the Netivot website and give it a well-deserved make-over.</p>
    <br />
    <%= image_tag("israel-path.jpg", class: "image left") %>
    <h4>Andy Rosenbaum, Shabbat Coordinator, Boston</h4>
    <p>As a new Netivot member, Andy is excited to dive into the heart of the Netivot experience - Shabbat dinners - and make them the best they can be.</p>
    <br />
    <%= image_tag("israel-path.jpg", class: "image left") %>
    <h4>Shira Frager, Secretary, Boston</h4>
    <p>As a new addition to the community, Shira is looking forward bringing her experiences and skills to Netivot.</p>
    <br /><br /><br />
    <%= image_tag("israel-path.jpg", class: "image left") %>
    <h4>Sara Fried, Education Chair, Boston</h4>
    <p>Sara will be continuing her role as Netivot's education chair, adding to her previous events, such as the discussion with Rabbi Rapoport and Netivot Network's launch event.</p>
  </section>